/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.1.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "backend"

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }

    // 这里声明插件版本，子模块 / convention plugins 都可用
    plugins {
        id("org.springframework.boot") version "3.3.5"
        id("io.spring.dependency-management") version "1.1.6"
        kotlin("jvm") version "1.9.25"
        kotlin("plugin.spring") version "1.9.25"
        kotlin("plugin.jpa") version "1.9.25"
        id("com.diffplug.spotless") version "6.25.0"
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}
//plugins {
//    // Apply the foojay-resolver plugin to allow automatic download of JDKs
//    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
//}

include("ledger", "list", "utilities")
include("auth")
include("market-stream")
include("quant-engine")
include("app")