/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ledgerx.ledger.api;

import com.jocelyn.ledger.MessageUtils;
import org.junit.jupiter.api.Test;

class MessageUtilsTest {
    @Test
    void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
